[platformio]
extra_configs = ../common/platformio.ini
include_dir = ../common

[env:pico32]
lib_deps =
    zinggjm/GxEPD2@1.6.4
    adafruit/Adafruit GFX Library@1.11.11
    adafruit/Adafruit BusIO@1.16.1
