(part "EVQ-PUA02K"
    (packageRef "EVQPUA02K")
    (interface
        (port "1" (symbPinId 1) (portName "NO_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "COM_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "NO_2") (portType INOUT))
        (port "4" (symbPinId 4) (portName "COM_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "162")
    (property "Mouser_Part_Number" "667-EVQ-PUA02K")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Panasonic/EVQ-PUA02K?qs=whhzBCqEXCvFsgipcL1tig%3D%3D")
    (property "Manufacturer_Name" "Panasonic")
    (property "Manufacturer_Part_Number" "EVQ-PUA02K")
    (property "Description" "Tactile Switches SIDE PUSH 2.2NF 4.7x3.2x1.65mm")
    (property "Datasheet_Link" "https://datasheet.datasheetarchive.com/originals/distributors/Datasheets-DGA6/577059.pdf")
    (property "symbolName1" "EVQ-PUA02K")
)
